### ISSUE TITLE
Smart quotes

### ISSUE THREAD

**Issue by kayserifserif** [coem-lang/lang-coem#1]
Provide information about converting dumb quotes ("") to smart quotes (“”) in CodeMirror? re this extension for the Agda language https://github.com/codewars/codemirror-unicode-helper/issues/1

**Comment by whykatherine** [comment]
https://github.com/codewars/codemirror-unicode-helper/issues/1

**Comment by kayserifserif** [comment]
resolved in https://github.com/coem-lang/coem-editor/commit/6b9dae9d66373bbb510a1a041c07d3a62d63a13d ?
